[[GettextRuntime]]
arch = "aarch64"
git-tree-sha1 = "68fec790089d6902a92f7eb66e626b7a0147d017"
os = "macos"

    [[GettextRuntime.download]]
    sha256 = "e5d6b93b3f14ee753b02e65c0f17b7f5cf7672491e3a7897d14c45354d3e8019"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.aarch64-apple-darwin.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce22446b6b0d9784a6f4672090d4fc94a71bd8ad"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "c3a49c0a4907757faf1e27df46c271af7b209f3abbf6667e2ce45695df0449da"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fea28b89994d170d444e3f3a0ad285b4bc8b8af2"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "8939df7a6a929aceb118324ca10af495ec75923fbe7829e8a378d6f0aebc6cf8"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b223e77a844c8d1f2e12a091be33d9e0138e48ce"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "1c0cd68af51f947d00563ddb2b7105c2d5445602bb10dee29d6387f073357643"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.aarch64-linux-musl-cxx03.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac69b79c1db7a9b2617a75be8619102cb941c908"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "60ef96d4afc5b04aa2b5b668da5fb83c56b07fb6a191b883148d1ed0bc89b8a7"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.aarch64-linux-musl-cxx11.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
git-tree-sha1 = "d92258ed39925fdae184f2ad7fb01dd29117db44"
os = "freebsd"

    [[GettextRuntime.download]]
    sha256 = "e61fe34097f0edd8f0d5fd62c8c870b9dd9a2acea69f1bf6e3b1b0a45d4a9ee3"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.aarch64-unknown-freebsd.tar.gz"
[[GettextRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eaafa1fe88ae04b6f7a60707be7d1913837c283f"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "6898d2054794df132f873daf574537550a257a5556512c38f24eb489ecaebda4"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GettextRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d16f9f44d9bbd9bba6bc67bf4fdf94d2e622fbff"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "0f95cad03aba7ef19b418322f91d7afc86a06f34f1419fe7613c323a26a94a77"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GettextRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c94252336df474f31164aa62c7a20532e50a37c1"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "5c293d992300a92666ad0184845ad72a57bb219992cd9150c25c861f7deeda89"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GettextRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3322f7354ce2e1bee94b2771c298c238e868f33b"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "9e684f8ff4a1a1849a5009fd4df67bebee14c45f83112c22979799e2c3805066"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GettextRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97ca97a30a5d8fe9675102c32e2a921621d4ec15"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "aa5c7e6e53084540269c6d8f1fa5d1ea14c85bc793ae66f3e5580d0890bd08dd"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GettextRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "333436e87ab8b2b24ab7945114d8ef55bbd19dc0"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "a4a2216098bfa1d9437a0196552e3f1fb58308e70e30d238f659dfb557528cd2"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GettextRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5d085285c8ba585779bbc462640c2b55b38c44b"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "9581db6038fa30b5c8204c5cd48a44e9cfc8188e39b54bbfb07d1c42332236b6"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GettextRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71ba4b00a5edeb3f1257736768de887bc4983605"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "783fad6987bd4a2c4a359e55b60974733154e17e15cd72b73015a71fa8fcdf5a"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c845cb00c912bc7f7fe20bf9bc5bbeaa3b83b01"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "346073bef7f4523631011ad4080574b02e96c9d7ed8fdac77375a465ac0c259e"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.i686-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c372ec95568aae13d8ce75aeadc9f2b6d99850ad"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "4e47e7002c5ea46ecf0fb4a0dd22116994b846c81d8181e4d4731c1b5fe327dd"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.i686-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab5dfc0f6ce900370dd5870368cc72e7a7927449"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "62a1a23425547ef5186fd866d5326aac4199fa5831b21a90de4bd9c40be4e502"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.i686-linux-musl-cxx03.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c066966556c7aa6d0c1980b1b7aa59549806e3e5"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "cf348a4e54acff7a7729ae88e63218f640f135fced91c179b4d32b83fd6378e3"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.i686-linux-musl-cxx11.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41b1eb44d913b34bd360d1fdd549eecfc2440fa1"
os = "windows"

    [[GettextRuntime.download]]
    sha256 = "beb2263ead2070bfeb94120fef266eb5212d26bdfefff897bc0e6bfd63889524"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.i686-w64-mingw32-cxx03.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "978b4eece4ff88590d2df9384a3a73075d8e2eaa"
os = "windows"

    [[GettextRuntime.download]]
    sha256 = "b06e13529dc9327dceefc51c202808924994a2cbdac9710cab2e14514d05d687"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.i686-w64-mingw32-cxx11.tar.gz"
[[GettextRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "751565b20903a8819e65d5d93c2ee230fe2ca13c"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "6bc3908e465e5e8bc5a4738bdc8db0373df0a33d4e4a88f34a6071c2dbeb07f9"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2b815bd3828371015b309ec011a284d9172a395"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "d79cb2e299f4c7a44b30a1088d9ad2b1fa671f19304fd0f910c649b813218e21"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7a418c9f93da83df5e2d716c0b3960d9438c74a"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "48323b5e2301e76ec78a900cef32ec89d34da4494e5f6a785d904f8a6eeffff7"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.riscv64-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd3928ca91b809674f05769090a13794210d423b"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "bd98b9f9fb5023221ecf4a768068c8cf006a012d17dd5e11971ecb1328b237c3"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.riscv64-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
git-tree-sha1 = "a9d1fdabaf01ce0b9bcdc6867ccfe103e5f63108"
os = "macos"

    [[GettextRuntime.download]]
    sha256 = "7fe2a7b17ae9578c048cead972b18ed84f74c089fc58ca204ea177ace2ca4197"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.x86_64-apple-darwin.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67445a8d8be1223edf1b55deb25faa6909af2663"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "d451d5f05eda1f16c478777b994174e4ccc502901fd500f90c1410203b178d0e"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "210271f13c9ba7cf07aeeb31b35ef23cba1605d6"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "162d9568872ffc0860cf868676be9a4228a47a706ca2e5512af6d617d9357a2a"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42f47946445763bbc78d0dad990b81d850b44077"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "cb68304f390e8ddfcb19a9cb58ec1cf6ad30d21797c3d9e40add8b5858e4325f"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.x86_64-linux-musl-cxx03.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1262c304834c730c02b9dfd935a0d2f6be3c648"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "723c837777da77f2033aac42936a1d69cecbe26473fa32e059805a6c865b27d6"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.x86_64-linux-musl-cxx11.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
git-tree-sha1 = "50ca86115a3d841068d7f503346015b10ef0aef4"
os = "freebsd"

    [[GettextRuntime.download]]
    sha256 = "7e1f522a8dbff0c11c561c6f43375b6ad53b14ce647b11a81e7901c0fd4ab36c"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.x86_64-unknown-freebsd.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2ef8bb9f04157c06d9a5c1f7b73a71389973036"
os = "windows"

    [[GettextRuntime.download]]
    sha256 = "b2925ea8de585f58594e1c857084eeb70eeaa6ec3e95158b2a6ae4209097a281"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5145368d9a189b9386a6f91695af3aac54dd7d14"
os = "windows"

    [[GettextRuntime.download]]
    sha256 = "bbe31854820ca844117f1e996d56a0a894f81c80968f138c783de63f1e0e7265"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.25.0+0/GettextRuntime.v0.25.0.x86_64-w64-mingw32-cxx11.tar.gz"
