[[GettextRuntime]]
arch = "aarch64"
git-tree-sha1 = "c87c6179c16bc4417756685195ab9cc6cb6215cf"
os = "macos"

    [[GettextRuntime.download]]
    sha256 = "141ee70964bfdd4a9e4ead70891ff1efd8fd6119793c28f9c41a7dfdf548daba"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.aarch64-apple-darwin.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "355a2ee26856d48a192b4588040a0384e25624fe"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "458cc043d991a62fb97456387f0b61b2ac4e7ae72afebd5be87a7b23e638d1a2"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f4acb35e20a171f008e471bd91f7c1b0e13d26c"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "fcac05beaabb326f68680f1dcf1d0d5f8a19df9ff53233d11a4e47e8aded206d"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e799f2af2dc6848df506ce8a280601e149bc3e4c"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "5d3cfd1b6d3e09a0b752fea3200070a134ad9fd3522779d7423940fbbb300528"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.aarch64-linux-musl-cxx03.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d903365e002294dc9c635a9bafa353378087279c"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "32dbc6b3a6258efb89a0621ea45686726a987ede0e64c1187bb7fb0db73eb3d1"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.aarch64-linux-musl-cxx11.tar.gz"
[[GettextRuntime]]
arch = "aarch64"
git-tree-sha1 = "4fb38f4e73d72fbbceee212c43a76eeb392c8cbd"
os = "freebsd"

    [[GettextRuntime.download]]
    sha256 = "2cae4986d036ecc936a8f0bbfe80d7ef9a1cf4a1d5430c195cd4879d2fc6a519"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.aarch64-unknown-freebsd.tar.gz"
[[GettextRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd9f98929dcfb7d48d59195f00249eda4389655a"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "d5e3a7f0ebea78f4e17852325b75e96e905200b6e3f73ba2c39639337af61e45"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GettextRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03dcf9de32060e5a8b114ae0ebabb56056018d18"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "27b349fcd6c5aa4095ee555c7751e54a35b22b0628027fc3da7ed1a35becf141"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GettextRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0ec3f71349ba74c65ae5aa2e63faac15c7ce178"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "5dca2fab99d9bb7f0724831ec03c0e689afe1b1f2df787ef6ba23152423ae3c8"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GettextRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0b7191a36ac73a64c90ef4cfa0c4a875ddf56e0"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "e6d963ec3f332269ed2cca7e1f22af299f8f319852c7d68dbfe63dc447fab25e"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GettextRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6de7e93b41c654b53e2173d2b5d6b0f1cabbc9fa"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "190bb4d5169790a020815b68ebb8a7a6ee92731f5428842e62dda30cd8138e1a"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GettextRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5941cb907e14a2d444801ad05da528f00598175"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "27863f3e50b333ab48dc90198a6c311fcdcdd137623801bf13a0a3b67a81aa70"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GettextRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2883f2838cdc3bb6f786e3911ac529fd2cdaa7b2"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "694ef179b5f039d30e4a6f2f1bc22f6cfd9fd6ea81fedda890715b5ce9458d30"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GettextRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32fb96a9e0d1e894f486df635d83e9642add6287"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "76d389f7abb61b2f4c8a28b1642e5869ffb194f6dd976ee99ed11a6c2aaa5c46"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4753ca6fbd7e515d0d22887a8a0510fd7c787da4"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "c45b4bd2114031e8527cd4234c2843729eb89b7c42d93bf7196ebf18e379fa6d"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.i686-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9427dbea63896adc9c97132ad65aa4954ed87c25"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "5e4016fbe3e4a17d9e2957d7c369f027e8fa05368f30d851af76c9b8ea6f208b"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.i686-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c60ce4951224394bf3e17f017bd68d7b2494837"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "4f54d7ee5a86c7b072405ae21b82879de49e9b61f7fd81f43d51e69c47b65752"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.i686-linux-musl-cxx03.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "013a575864544cb64e71370038ef9e52a03ae203"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "85150a7015212b4bc2433dd8cb81c7ca2ddb93a66884147514b7629e274389b7"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.i686-linux-musl-cxx11.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "402d5ff0163f70a1e5730960443d9af0f268df81"
os = "windows"

    [[GettextRuntime.download]]
    sha256 = "393e00e88a9b4fc57463c08facf24dcd52badc7ad5e1fb0280136ac5402dcd2e"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.i686-w64-mingw32-cxx03.tar.gz"
[[GettextRuntime]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64fe9c8a0f3d1ce2c387d8564349d5c85a249deb"
os = "windows"

    [[GettextRuntime.download]]
    sha256 = "d49187da7f90e302fab219ea5b8b18c6820bc21d0cdcbf90c9ffd96b94c0b664"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.i686-w64-mingw32-cxx11.tar.gz"
[[GettextRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fab42f6221ea6ea50c48c7dc18290ee9e7b17f9e"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "f2f49a0bd6e87eff95b5292f1cef9b9bd6d793c881d4f1713c30804a9e30cccb"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8a0713e3a29cdc900ac21b3e8263871d62fc61f"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "b437c9818ae1bffc2beb52ee77f7176f267f9cdd7ff276d238c2f1ee48773f9c"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cf0aca51f16600c1f6b5a2e92256d4c521cb16f"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "42be0c83089d6056f75fc50f653f9465628ee74360f03d774de8ec524dbca714"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.riscv64-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f7e5e90e7feb2bbc94d914c5a5e3e4ad16ab335"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "ab89bcd8ca348658218057293fce06546cf237dfa8050c23ec5b4d3b172f474e"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.riscv64-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
git-tree-sha1 = "f855c7aa4c13290d2c2e4ee634d32f0a77a0d5ea"
os = "macos"

    [[GettextRuntime.download]]
    sha256 = "17c5ebfb61d460c987fe7f727280b3aaa0ba987972e1b5e86cdd2a58a9f67d89"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.x86_64-apple-darwin.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ffe9e36f3bc7d662a4815b96f82338e241b5c94"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "37177d28e5a2451f0528fcb76909fee2969c6a968b688c6ac6de57f38f52735a"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f79a0d9f230ee1324ae490ae5b5cec879a7d8c73"
libc = "glibc"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "fc2b642c3ff8d5ea294859588958ab17efc17762fe9565a7837dacfe8a53375c"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "563dc73519681d2a414b1c82a1c8b06b7ee7668a"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "95dfabd86389b2886aa0eaf1e1b0e381f79efdc6731f681a652c61b3cd320f1f"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.x86_64-linux-musl-cxx03.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f65ca6e04cee2aa28e911588a4d05a85902797dc"
libc = "musl"
os = "linux"

    [[GettextRuntime.download]]
    sha256 = "a06b1e361151f626642d536c730f8b891659d393e8f8b23f8179a20aca269f7f"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.x86_64-linux-musl-cxx11.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
git-tree-sha1 = "2eeae74b69d34c24dbfed59c0547d5da2209c5ef"
os = "freebsd"

    [[GettextRuntime.download]]
    sha256 = "e15f26bb347df664fcd086aa5ec3fa673fb67e57b8504628d488e59b2f9faddf"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.x86_64-unknown-freebsd.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfca055373242a8b1086419535a0d4e1425425fc"
os = "windows"

    [[GettextRuntime.download]]
    sha256 = "3e46c6bada408628686aa954c596295d789451ea4eaf2aa075167fa40b226c51"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GettextRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2046333816175796f8e52a5c2e392e0f4ae9903"
os = "windows"

    [[GettextRuntime.download]]
    sha256 = "b4e4cb3a63ccc5ad09ec4b520345f14de39ee04fd7169419c9dcddc739b427ca"
    url = "https://github.com/nhz2/GettextRuntime_jll.jl/releases/download/GettextRuntime-v0.24.0+0/GettextRuntime.v0.24.0.x86_64-w64-mingw32-cxx11.tar.gz"
